{
    __Schema:__type(name:"__Schema") {
        name:fullName
        kind
    }
    __TypeKind:__type(name:"__TypeKind") {
        name:fullName
        kind
        enumValues {
            name
        }
    }
    String:__type(name:"String") {
        name:fullName
        kind
        fields
    }
    __Type:__type(name:"__Type") {
        name:fullName
        kind
        fields {
            name
            typeName
        }
    }
    PersonPlanetInterface:__type(name:"PersonPlanetInterface") {
        name:fullName
        kind
        fields {
            name
            typeName
        }
        possibleTypes {
            fullName
        }
    }
    PersonPlanetUnion:__type(name:"PersonPlanetUnion") {
        name:fullName
        kind
        fields {
            name
            typeName
        }
        possibleTypes {
            fullName
        }
    }
}
