{
    __Schema:__type(name:"__Schema") {
        name:fullName
        kind
    }
    __TypeKind:__type(name:"__TypeKind") {
        name:fullName
        kind
    }
    String:__type(name:"String") {
        name:fullName
        kind
#        fields
    }
    __Type:__type(name:"__Type") {
        name:fullName
        kind
#        fields {
#            name
#        }
    }
}
