type Query {
    __schema: __Schema!
    __type(name: String!): __Type

    isListTrue: [Boolean]
    isListFalse: Boolean
    isNotListTrue: [Boolean]
    isNotListFalse: Boolean

    string(value:String): String
    int(value:String): Int
    boolean(value:String): Boolean
    float(value:String): Float
    nonNull(value:String): String!

    testEnum(value:TestEnum): [TestEnum]
}

enum TestEnum {
    A
    B
    C
}