extend type Query {
    __schema: __Schema!
}

type Query {
    allPeople: PeopleConnection
    allPlanets: PlanetsConnection
    interfaces: [PersonPlanetInterface!]
    interface: PersonPlanetInterface
    unions: [PersonPlanetUnion!]
    union: PersonPlanetUnion
}

extend type Query {
    __type(name: String!): __Type
}

type PageInfo {
    hasNextPage: Boolean!
    hasPreviousPage: Boolean!
    startCursor: String
    endCursor: String
}

type PeopleConnection {
    pageInfo: PageInfo!
    edges: [PeopleEdge]
    totalCount: Integer
    people: [Person]
}

type PeopleEdge {
    node: Person
    cursor: String!
}

type Person implements PersonPlanetInterface {
    id: ID!
    name: String
    birthYear: String
    eyeColor: String
    gender: String
    hairColor: String
    height: Int
    mass: Float
    skinColor: String
    homeworld: Planet
    filmConnection: PersonFilmsConnection
    species: Species
    starshipConnection: PersonStarshipsConnection
    vehicleConnection: PersonVehiclesConnection
    created: String
    edited: String
}

type PersonFilmsConnection {
    id: ID!
}

type PersonStarshipsConnection {
    id: ID!
}

type PersonVehiclesConnection {
    id: ID!
}

type Species {
    id: ID!
}

type PlanetResidentsConnection {
    id: ID!
}

type PlanetFilmsConnection {
    id: ID!
}

type PlanetsConnection {
    pageInfo: PageInfo!
    edges: [PlanetsEdge]
    totalCount: Integer
    planets: [Planet]
}

type PlanetsEdge {
    node: Planet
    cursor: String!
}

type Planet implements PersonPlanetInterface {
    name: String
    diameter: Int
    rotationPeriod: Int
    orbitalPeriod: Int
    gravity: String
    population: Float
    climates: [String]
    terrains: [String]
    surfaceWater: Float
    residentConnection: PlanetResidentsConnection
    filmConnection: PlanetFilmsConnection
    created: String
    edited: String
    id: ID!
}

union PersonPlanetUnion = Person | Planet

interface PersonPlanetInterface {
    id: ID!
    name: String
}
