{
    allPeople {
        people {
            ... on Person {
                a:name
            }
            ... Person
        }
    }
    allPlanets {
        planets {
            ... on Planet {
                a:name
            }
            ... Planet
        }
    }
}

fragment Planet on Planet {
    b:name
}

fragment Person on Person {
    b:name
}
